version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "timrogers"
    commit-message:
      prefix: "deps"
      include: "scope"